### ISSUE TITLE
v4.0.0 (Version number 3.9.0 not updated)

### ISSUE THREAD

**Issue by claus-e-andersen** [OpenTOPAS/OpenTOPAS#15]
### Discussed in https://github.com/OpenTOPAS/OpenTOPAS/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **JoseRamosMendez** April 30, 2024</sup>
Compatible with Geant4.11.1.3

<hr /><em>This discussion was created from the release <a href='https://github.com/OpenTOPAS/OpenTOPAS/releases/tag/'>v4.0.0</a>.</em></div>

**Comment by JNaokiDKondo** [comment]
Merge Pull request done. Closing issue.
