### ISSUE TITLE
[Issue]: ENSDFSTATE invalid data value

### ISSUE THREAD

**Issue by leehoy** [OpenTOPAS/OpenTOPAS#21]
### What was the issue?

I'm trying to simulate 30 keV gamma to obtain optical photon signals. When I try to run the simulation it says there is an invalid value in G4ENSDFSTATE2.3 data.
![output](https://github.com/OpenTOPAS/OpenTOPAS/assets/3752557/0883165c-a605-4b94-a06f-4ad51482e474)

### Version

4.0

### What Operative System (OS) are you running on?

Linux

### Relevant log output

```shell
-------- EEEE ------- G4Exception-START -------- EEEE -------

*** G4Exception : PART70002
      issued by : G4NuclideTable
5.609049e+17 is not valid indicator of G4Ions::G4FloatLevelBase.
You may use a wrong version of ENSDFSTATE data.
Please use G4ENSDFSTATE-2.0 or later.
*** Fatal Exception *** core dump ***
 **** Track information is not available at this moment
 **** Step information is not available at this moment

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Attestation

- [X] I testify that I have fully read the bug reporting guideline beforehand.

**Comment by leehoy** [comment]
Could be something on Geant4 side

**Comment by JoseRamosMendez** [comment]
It looks like a ENSDFSTATE version issue. Can you share a bit of your parameter file to allow us to reproduce your error?

**Comment by leehoy** [comment]
While I was trying to resolve the issue, it's gone without any changes. Maybe it was a false alarm. I will close the issue.
